title = "Muza"
baseURL = "mzakdr.com"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"
hasCJKLanguage = false
paginate = 3
rssLimit = 20
disqusShortname = ""
googleAnalytics = ""
copyright = ""
defaultContentLanguage = "en"

[languages]

[languages.en]
languageCode = ""

[author]
name = "muza"

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[menu]

[[menu.main]]
identifier = "home"
name = "This is Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/post/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 40

[[menu.main]]
name = "external-link"
url = "https://quran.com/72"
weight = 50

[params]
contentCopyright = "<a rel=\"license noopener\" href=\"https://creativecommons.org/licenses/by-nc-nd/4.0/\" target=\"_blank\">CC BY-NC-ND 4.0</a>"
customCSS = []
customJS = []
dateFormatToUse = "2006-Jan-02"
description = "mzakdr's dreams and aspirations"
homeFullContent = false
keywords = ["mzakdr", "blog", "note"]
logoTitle = "Muza"
photoswipe = true
rssFullContent = true
since = "2019"
toc = true

[params.social]
a-email = "mailto:mzakdr@gmail.com"
b-stack-overflow = ""
c-twitter = "http://twitter.com/mzakdr"
d-facebook = ""
e-linkedin = "linkedin.com/in/muzaabdul"
f-google = ""
g-github = "github.com/mzakdr"
h-weibo = ""
i-zhihu = ""
j-douban = ""
k-pocket = ""
l-tumblr = ""
m-instagram = "instagram.com/mzakdr"
n-gitlab = ""
o-goodreads = ""
p-coding = ""
q-bilibili = ""
r-codeforces = ""
s-mastodon = ""